const Const = {
  zenduForms: "ZenduForms",
  forms: "Forms",
  customers: "Customers",
  submittsions: "Submissions",
  history: "History",
  reports: "Reports",
  workflow: "Workflow",
  search: "Search",
  selectForms: "Select Form",
  selectStatus: "Select Status",
  map: "Map",
  list: "List",
  export: "Export",
  dataExport: "Data Exported Successfully",
  logout: "Logout",
  notifications: "Notifications",
  notificationClicked: "Notifications Clicked.",
  logoutSuccess: "Log out Successful",
  submissions: "Submissions",
  mapSmall: "map",
  falseStr: "false",
  listSmall: "list",
  displayList: "Table List will be displayed over here",
};
export default Const;
